// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafotJQZykRUQ0VVplYw-EOJVUG5UJw7I',
    appId: '1:902215494671:web:e744c49d464bc05457077a',
    messagingSenderId: '902215494671',
    projectId: 'sparkle-674ee',
    authDomain: 'sparkle-674ee.firebaseapp.com',
    storageBucket: 'sparkle-674ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDSki7HdDn3L3wuDJXYdCVLoRTKBgXEw',
    appId: '1:902215494671:android:7c97a02fa9f24faa57077a',
    messagingSenderId: '902215494671',
    projectId: 'sparkle-674ee',
    storageBucket: 'sparkle-674ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgn0aGEboihf4rDSvlSoaUPU8DxSqWmI',
    appId: '1:902215494671:ios:5427a80538e1778757077a',
    messagingSenderId: '902215494671',
    projectId: 'sparkle-674ee',
    storageBucket: 'sparkle-674ee.appspot.com',
    iosBundleId: 'com.example.sparkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMgn0aGEboihf4rDSvlSoaUPU8DxSqWmI',
    appId: '1:902215494671:ios:e79e61996358a38b57077a',
    messagingSenderId: '902215494671',
    projectId: 'sparkle-674ee',
    storageBucket: 'sparkle-674ee.appspot.com',
    iosBundleId: 'com.example.sparkle.RunnerTests',
  );
}
